title: Subterranean District
description: The district beneath the surface.
theme: minima
markdown: kramdown
permalink: /:categories/:title/

header_pages:
  - manifesto.md
  - archive.md
  - about.md
